"""
data_collector.py — Builds raw DataFrames for LLMs Assemble.
Zero file I/O. Both public functions return pd.DataFrame.
"""
from __future__ import annotations

import numpy as np
import pandas as pd


def build_static_dataset() -> pd.DataFrame:
    """Return a 40-row DataFrame with all raw LLM benchmark and operational data."""
    records = [
        {
            "model_name": "GPT-4o",
            "organization": "OpenAI",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 200.0,
            "context_window_k": 128,
            "mmlu_score": 88.7,
            "humaneval_score": 90.2,
            "math_score": 76.6,
            "hellaswag_score": 95.3,
            "arc_score": 96.3,
            "tokens_per_second": 109.0,
            "latency_ms": 320.0,
            "cost_input_per_1m": 5.0,
            "cost_output_per_1m": 15.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-05",
        },
        {
            "model_name": "GPT-4o mini",
            "organization": "OpenAI",
            "architecture": "Transformer",
            "parameter_size_b": 8.0,
            "context_window_k": 128,
            "mmlu_score": 82.0,
            "humaneval_score": 87.2,
            "math_score": 70.2,
            "hellaswag_score": 89.1,
            "arc_score": 88.3,
            "tokens_per_second": 180.0,
            "latency_ms": 180.0,
            "cost_input_per_1m": 0.15,
            "cost_output_per_1m": 0.60,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-07",
        },
        {
            "model_name": "GPT-4 Turbo",
            "organization": "OpenAI",
            "architecture": "Transformer",
            "parameter_size_b": 1800.0,
            "context_window_k": 128,
            "mmlu_score": 86.4,
            "humaneval_score": 87.1,
            "math_score": 72.2,
            "hellaswag_score": 95.4,
            "arc_score": 96.4,
            "tokens_per_second": 42.0,
            "latency_ms": 780.0,
            "cost_input_per_1m": 10.0,
            "cost_output_per_1m": 30.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-04",
        },
        {
            "model_name": "GPT-3.5 Turbo",
            "organization": "OpenAI",
            "architecture": "Transformer",
            "parameter_size_b": 20.0,
            "context_window_k": 16,
            "mmlu_score": 70.0,
            "humaneval_score": 73.5,
            "math_score": 57.1,
            "hellaswag_score": 85.5,
            "arc_score": 85.2,
            "tokens_per_second": 67.0,
            "latency_ms": 450.0,
            "cost_input_per_1m": 0.5,
            "cost_output_per_1m": 1.5,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2023-03",
        },
        {
            "model_name": "Claude 3.5 Sonnet",
            "organization": "Anthropic",
            "architecture": "Transformer",
            "parameter_size_b": 175.0,
            "context_window_k": 200,
            "mmlu_score": 88.3,
            "humaneval_score": 92.0,
            "math_score": 71.1,
            "hellaswag_score": 89.1,
            "arc_score": 93.2,
            "tokens_per_second": 79.0,
            "latency_ms": 380.0,
            "cost_input_per_1m": 3.0,
            "cost_output_per_1m": 15.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-06",
        },
        {
            "model_name": "Claude 3.5 Haiku",
            "organization": "Anthropic",
            "architecture": "Transformer",
            "parameter_size_b": 20.0,
            "context_window_k": 200,
            "mmlu_score": 77.9,
            "humaneval_score": 88.2,
            "math_score": 69.2,
            "hellaswag_score": 86.0,
            "arc_score": 88.5,
            "tokens_per_second": 200.0,
            "latency_ms": 150.0,
            "cost_input_per_1m": 0.8,
            "cost_output_per_1m": 4.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-01",
        },
        {
            "model_name": "Claude 3 Opus",
            "organization": "Anthropic",
            "architecture": "Transformer",
            "parameter_size_b": 175.0,
            "context_window_k": 200,
            "mmlu_score": 86.8,
            "humaneval_score": 84.9,
            "math_score": 60.1,
            "hellaswag_score": 95.4,
            "arc_score": 96.4,
            "tokens_per_second": 20.0,
            "latency_ms": 1200.0,
            "cost_input_per_1m": 15.0,
            "cost_output_per_1m": 75.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-03",
        },
        {
            "model_name": "Claude 3 Haiku",
            "organization": "Anthropic",
            "architecture": "Transformer",
            "parameter_size_b": 20.0,
            "context_window_k": 200,
            "mmlu_score": 75.2,
            "humaneval_score": 75.9,
            "math_score": 38.9,
            "hellaswag_score": 85.9,
            "arc_score": 87.4,
            "tokens_per_second": 142.0,
            "latency_ms": 210.0,
            "cost_input_per_1m": 0.25,
            "cost_output_per_1m": 1.25,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-03",
        },
        {
            "model_name": "Gemini 1.5 Pro",
            "organization": "Google",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 340.0,
            "context_window_k": 1000,
            "mmlu_score": 85.9,
            "humaneval_score": 84.1,
            "math_score": 67.7,
            "hellaswag_score": 92.5,
            "arc_score": 88.0,
            "tokens_per_second": 50.0,
            "latency_ms": 850.0,
            "cost_input_per_1m": 3.5,
            "cost_output_per_1m": 10.5,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-05",
        },
        {
            "model_name": "Gemini 1.5 Flash",
            "organization": "Google",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 80.0,
            "context_window_k": 1000,
            "mmlu_score": 78.9,
            "humaneval_score": 74.3,
            "math_score": 54.9,
            "hellaswag_score": 89.2,
            "arc_score": 86.5,
            "tokens_per_second": 150.0,
            "latency_ms": 290.0,
            "cost_input_per_1m": 0.075,
            "cost_output_per_1m": 0.30,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-05",
        },
        {
            "model_name": "Gemini 2.0 Flash",
            "organization": "Google",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 100.0,
            "context_window_k": 1000,
            "mmlu_score": 85.0,
            "humaneval_score": 90.5,
            "math_score": 75.6,
            "hellaswag_score": 91.0,
            "arc_score": 90.2,
            "tokens_per_second": 220.0,
            "latency_ms": 140.0,
            "cost_input_per_1m": 0.1,
            "cost_output_per_1m": 0.40,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-02",
        },
        {
            "model_name": "Llama 3.1 405B",
            "organization": "Meta",
            "architecture": "Transformer",
            "parameter_size_b": 405.0,
            "context_window_k": 128,
            "mmlu_score": 88.6,
            "humaneval_score": 89.0,
            "math_score": 73.8,
            "hellaswag_score": 92.8,
            "arc_score": 94.5,
            "tokens_per_second": 15.0,
            "latency_ms": 1800.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-07",
        },
        {
            "model_name": "Llama 3.1 70B",
            "organization": "Meta",
            "architecture": "Transformer",
            "parameter_size_b": 70.0,
            "context_window_k": 128,
            "mmlu_score": 83.6,
            "humaneval_score": 80.5,
            "math_score": 65.7,
            "hellaswag_score": 87.3,
            "arc_score": 91.1,
            "tokens_per_second": 45.0,
            "latency_ms": 650.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-07",
        },
        {
            "model_name": "Llama 3.1 8B",
            "organization": "Meta",
            "architecture": "Transformer",
            "parameter_size_b": 8.0,
            "context_window_k": 128,
            "mmlu_score": 73.0,
            "humaneval_score": 72.6,
            "math_score": 51.9,
            "hellaswag_score": 82.0,
            "arc_score": 84.2,
            "tokens_per_second": 130.0,
            "latency_ms": 280.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-07",
        },
        {
            "model_name": "Llama 3.2 3B",
            "organization": "Meta",
            "architecture": "Transformer",
            "parameter_size_b": 3.0,
            "context_window_k": 128,
            "mmlu_score": 63.4,
            "humaneval_score": 58.0,
            "math_score": 41.6,
            "hellaswag_score": 75.3,
            "arc_score": 76.1,
            "tokens_per_second": 280.0,
            "latency_ms": 110.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-09",
        },
        {
            "model_name": "Mistral Large 2",
            "organization": "Mistral",
            "architecture": "Transformer",
            "parameter_size_b": 123.0,
            "context_window_k": 128,
            "mmlu_score": 84.0,
            "humaneval_score": 92.0,
            "math_score": 68.0,
            "hellaswag_score": 89.2,
            "arc_score": 93.0,
            "tokens_per_second": 38.0,
            "latency_ms": 920.0,
            "cost_input_per_1m": 2.0,
            "cost_output_per_1m": 6.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2024-07",
        },
        {
            "model_name": "Mistral 7B",
            "organization": "Mistral",
            "architecture": "Transformer",
            "parameter_size_b": 7.0,
            "context_window_k": 32,
            "mmlu_score": 64.2,
            "humaneval_score": 40.7,
            "math_score": 28.4,
            "hellaswag_score": 81.3,
            "arc_score": 79.9,
            "tokens_per_second": 95.0,
            "latency_ms": 310.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2023-09",
        },
        {
            "model_name": "Mixtral 8x7B",
            "organization": "Mistral",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 46.0,
            "context_window_k": 32,
            "mmlu_score": 70.6,
            "humaneval_score": 40.2,
            "math_score": 28.4,
            "hellaswag_score": 86.7,
            "arc_score": 85.9,
            "tokens_per_second": 80.0,
            "latency_ms": 420.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2023-12",
        },
        {
            "model_name": "Qwen2.5 72B",
            "organization": "Alibaba",
            "architecture": "Transformer",
            "parameter_size_b": 72.0,
            "context_window_k": 128,
            "mmlu_score": 86.0,
            "humaneval_score": 85.9,
            "math_score": 73.2,
            "hellaswag_score": 86.7,
            "arc_score": 91.0,
            "tokens_per_second": 40.0,
            "latency_ms": 700.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-09",
        },
        {
            "model_name": "Qwen2.5 7B",
            "organization": "Alibaba",
            "architecture": "Transformer",
            "parameter_size_b": 7.0,
            "context_window_k": 128,
            "mmlu_score": 74.2,
            "humaneval_score": 72.8,
            "math_score": 58.5,
            "hellaswag_score": 80.1,
            "arc_score": 82.3,
            "tokens_per_second": 150.0,
            "latency_ms": 260.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-09",
        },
        {
            "model_name": "DeepSeek-V3",
            "organization": "DeepSeek",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 671.0,
            "context_window_k": 128,
            "mmlu_score": 88.5,
            "humaneval_score": 89.3,
            "math_score": 75.4,
            "hellaswag_score": 88.9,
            "arc_score": 90.5,
            "tokens_per_second": 60.0,
            "latency_ms": 600.0,
            "cost_input_per_1m": 0.14,
            "cost_output_per_1m": 0.28,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-12",
        },
        {
            "model_name": "DeepSeek-R1",
            "organization": "DeepSeek",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 671.0,
            "context_window_k": 128,
            "mmlu_score": 90.8,
            "humaneval_score": 92.0,
            "math_score": 79.8,
            "hellaswag_score": 91.2,
            "arc_score": 92.7,
            "tokens_per_second": 40.0,
            "latency_ms": 900.0,
            "cost_input_per_1m": 0.55,
            "cost_output_per_1m": 2.19,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2025-01",
        },
        {
            "model_name": "Phi-3 Medium",
            "organization": "Microsoft",
            "architecture": "Transformer",
            "parameter_size_b": 14.0,
            "context_window_k": 128,
            "mmlu_score": 78.0,
            "humaneval_score": 70.9,
            "math_score": 53.6,
            "hellaswag_score": 83.2,
            "arc_score": 85.3,
            "tokens_per_second": 75.0,
            "latency_ms": 480.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-05",
        },
        {
            "model_name": "Phi-3 Mini",
            "organization": "Microsoft",
            "architecture": "Transformer",
            "parameter_size_b": 3.8,
            "context_window_k": 128,
            "mmlu_score": 68.8,
            "humaneval_score": 58.1,
            "math_score": 37.9,
            "hellaswag_score": 75.6,
            "arc_score": 77.8,
            "tokens_per_second": 160.0,
            "latency_ms": 220.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2024-04",
        },
        {
            "model_name": "Command R+",
            "organization": "Cohere",
            "architecture": "Transformer",
            "parameter_size_b": 104.0,
            "context_window_k": 128,
            "mmlu_score": 75.7,
            "humaneval_score": 60.0,
            "math_score": 33.8,
            "hellaswag_score": 88.1,
            "arc_score": 90.0,
            "tokens_per_second": 44.0,
            "latency_ms": 780.0,
            "cost_input_per_1m": 3.0,
            "cost_output_per_1m": 15.0,
            "is_open_source": False,
            "data_quality": "estimated",
            "release_month": "2024-04",
        },
    ]

    records += [
        {
            "model_name": "GPT-5",
            "organization": "OpenAI",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 1000.0,
            "context_window_k": 128,
            "mmlu_score": 91.5,
            "humaneval_score": 93.0,
            "math_score": 82.0,
            "hellaswag_score": 96.0,
            "arc_score": 97.0,
            "tokens_per_second": 95.0,
            "latency_ms": 290.0,
            "cost_input_per_1m": 1.75,
            "cost_output_per_1m": 14.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-08",
        },
        {
            "model_name": "GPT-5 mini",
            "organization": "OpenAI",
            "architecture": "Transformer",
            "parameter_size_b": 15.0,
            "context_window_k": 128,
            "mmlu_score": 84.0,
            "humaneval_score": 88.0,
            "math_score": 74.0,
            "hellaswag_score": 90.0,
            "arc_score": 91.0,
            "tokens_per_second": 200.0,
            "latency_ms": 160.0,
            "cost_input_per_1m": 0.25,
            "cost_output_per_1m": 2.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-08",
        },
        {
            "model_name": "Claude Sonnet 4",
            "organization": "Anthropic",
            "architecture": "Transformer",
            "parameter_size_b": 175.0,
            "context_window_k": 200,
            "mmlu_score": 90.2,
            "humaneval_score": 93.7,
            "math_score": 78.5,
            "hellaswag_score": 91.5,
            "arc_score": 94.8,
            "tokens_per_second": 85.0,
            "latency_ms": 340.0,
            "cost_input_per_1m": 3.0,
            "cost_output_per_1m": 15.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-06",
        },
        {
            "model_name": "Claude Opus 4",
            "organization": "Anthropic",
            "architecture": "Transformer",
            "parameter_size_b": 500.0,
            "context_window_k": 200,
            "mmlu_score": 91.8,
            "humaneval_score": 95.0,
            "math_score": 81.2,
            "hellaswag_score": 93.0,
            "arc_score": 96.5,
            "tokens_per_second": 30.0,
            "latency_ms": 1100.0,
            "cost_input_per_1m": 5.0,
            "cost_output_per_1m": 25.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-06",
        },
        {
            "model_name": "Claude Haiku 4",
            "organization": "Anthropic",
            "architecture": "Transformer",
            "parameter_size_b": 20.0,
            "context_window_k": 200,
            "mmlu_score": 80.5,
            "humaneval_score": 89.5,
            "math_score": 72.0,
            "hellaswag_score": 87.5,
            "arc_score": 89.0,
            "tokens_per_second": 220.0,
            "latency_ms": 130.0,
            "cost_input_per_1m": 1.0,
            "cost_output_per_1m": 5.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-08",
        },
        {
            "model_name": "Gemini 2.5 Pro",
            "organization": "Google",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 340.0,
            "context_window_k": 1000,
            "mmlu_score": 89.5,
            "humaneval_score": 90.0,
            "math_score": 83.0,
            "hellaswag_score": 93.5,
            "arc_score": 92.0,
            "tokens_per_second": 60.0,
            "latency_ms": 750.0,
            "cost_input_per_1m": 1.25,
            "cost_output_per_1m": 10.0,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-03",
        },
        {
            "model_name": "Gemini 2.5 Flash",
            "organization": "Google",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 80.0,
            "context_window_k": 1000,
            "mmlu_score": 83.0,
            "humaneval_score": 82.5,
            "math_score": 74.0,
            "hellaswag_score": 91.0,
            "arc_score": 89.5,
            "tokens_per_second": 250.0,
            "latency_ms": 120.0,
            "cost_input_per_1m": 0.075,
            "cost_output_per_1m": 0.30,
            "is_open_source": False,
            "data_quality": "measured",
            "release_month": "2025-03",
        },
        {
            "model_name": "Gemini 3 Pro",
            "organization": "Google",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 500.0,
            "context_window_k": 1000,
            "mmlu_score": 93.0,
            "humaneval_score": 94.5,
            "math_score": 88.0,
            "hellaswag_score": 95.5,
            "arc_score": 97.5,
            "tokens_per_second": 55.0,
            "latency_ms": 800.0,
            "cost_input_per_1m": 2.0,
            "cost_output_per_1m": 12.0,
            "is_open_source": False,
            "data_quality": "estimated",
            "release_month": "2025-11",
        },
        {
            "model_name": "Llama 4 Scout",
            "organization": "Meta",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 109.0,
            "context_window_k": 10000,
            "mmlu_score": 85.5,
            "humaneval_score": 81.0,
            "math_score": 72.5,
            "hellaswag_score": 89.5,
            "arc_score": 90.0,
            "tokens_per_second": 110.0,
            "latency_ms": 400.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2025-04",
        },
        {
            "model_name": "Llama 4 Maverick",
            "organization": "Meta",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 400.0,
            "context_window_k": 1000,
            "mmlu_score": 88.0,
            "humaneval_score": 85.5,
            "math_score": 76.0,
            "hellaswag_score": 91.0,
            "arc_score": 92.5,
            "tokens_per_second": 40.0,
            "latency_ms": 900.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2025-04",
        },
        {
            "model_name": "Grok 3",
            "organization": "xAI",
            "architecture": "Transformer",
            "parameter_size_b": 300.0,
            "context_window_k": 128,
            "mmlu_score": 87.5,
            "humaneval_score": 88.0,
            "math_score": 79.0,
            "hellaswag_score": 91.5,
            "arc_score": 93.0,
            "tokens_per_second": 70.0,
            "latency_ms": 550.0,
            "cost_input_per_1m": 3.0,
            "cost_output_per_1m": 15.0,
            "is_open_source": False,
            "data_quality": "estimated",
            "release_month": "2025-02",
        },
        {
            "model_name": "Grok 4",
            "organization": "xAI",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 500.0,
            "context_window_k": 256,
            "mmlu_score": 90.5,
            "humaneval_score": 92.0,
            "math_score": 83.5,
            "hellaswag_score": 93.0,
            "arc_score": 95.0,
            "tokens_per_second": 60.0,
            "latency_ms": 620.0,
            "cost_input_per_1m": 3.0,
            "cost_output_per_1m": 15.0,
            "is_open_source": False,
            "data_quality": "estimated",
            "release_month": "2025-07",
        },
        {
            "model_name": "Qwen3 235B",
            "organization": "Alibaba",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 235.0,
            "context_window_k": 128,
            "mmlu_score": 88.5,
            "humaneval_score": 87.0,
            "math_score": 80.0,
            "hellaswag_score": 90.5,
            "arc_score": 92.0,
            "tokens_per_second": 35.0,
            "latency_ms": 850.0,
            "cost_input_per_1m": 0.0,
            "cost_output_per_1m": 0.0,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2025-04",
        },
        {
            "model_name": "DeepSeek-V3.2",
            "organization": "DeepSeek",
            "architecture": "Transformer-MoE",
            "parameter_size_b": 671.0,
            "context_window_k": 128,
            "mmlu_score": 90.0,
            "humaneval_score": 91.5,
            "math_score": 79.0,
            "hellaswag_score": 90.0,
            "arc_score": 92.0,
            "tokens_per_second": 65.0,
            "latency_ms": 560.0,
            "cost_input_per_1m": 0.14,
            "cost_output_per_1m": 0.28,
            "is_open_source": True,
            "data_quality": "measured",
            "release_month": "2025-09",
        },
        {
            "model_name": "Mistral Large 3",
            "organization": "Mistral",
            "architecture": "Transformer",
            "parameter_size_b": 200.0,
            "context_window_k": 128,
            "mmlu_score": 86.0,
            "humaneval_score": 90.0,
            "math_score": 73.0,
            "hellaswag_score": 90.5,
            "arc_score": 93.5,
            "tokens_per_second": 45.0,
            "latency_ms": 800.0,
            "cost_input_per_1m": 2.0,
            "cost_output_per_1m": 6.0,
            "is_open_source": False,
            "data_quality": "estimated",
            "release_month": "2025-07",
        },
    ]

    df = pd.DataFrame(records)
    # Enforce dtypes
    df["is_open_source"] = df["is_open_source"].astype(bool)
    return df


def build_monthly_dataset() -> pd.DataFrame:
    """
    Return a 480-row DataFrame (40 models × 12 months, 2025-01 through 2025-12).
    Uses numpy random seed=42 for reproducibility.
    Models unavailable before their release_month get NaN for metric columns.
    """
    from src.config import MONTHLY_SNAPSHOTS  # type: ignore[import]

    rng = np.random.default_rng(seed=42)

    static_df = build_static_dataset()

    benchmark_cols = [
        "mmlu_score",
        "humaneval_score",
        "math_score",
        "hellaswag_score",
        "arc_score",
    ]

    rows = []
    for _, model_row in static_df.iterrows():
        model_name: str = str(model_row["model_name"])
        release_month: str = str(model_row["release_month"])
        is_oss: bool = bool(model_row["is_open_source"])

        # Track running values (start from static)
        current: dict[str, float] = {
            "mmlu_score": float(model_row["mmlu_score"]),
            "humaneval_score": float(model_row["humaneval_score"]),
            "math_score": float(model_row["math_score"]),
            "hellaswag_score": float(model_row["hellaswag_score"]),
            "arc_score": float(model_row["arc_score"]),
            "tokens_per_second": float(model_row["tokens_per_second"]),
            "latency_ms": float(model_row["latency_ms"]),
            "cost_input_per_1m": float(model_row["cost_input_per_1m"]),
        }

        for month in MONTHLY_SNAPSHOTS:
            if month < release_month:
                # Model not yet released — all metrics NaN
                rows.append(
                    {
                        "month": month,
                        "model_name": model_name,
                        "mmlu_score": None,
                        "humaneval_score": None,
                        "math_score": None,
                        "hellaswag_score": None,
                        "arc_score": None,
                        "tokens_per_second": None,
                        "latency_ms": None,
                        "cost_input_per_1m": None,
                    }
                )
                continue

            # Apply monthly deltas
            for col in benchmark_cols:
                delta = float(rng.uniform(0.1, 0.8))
                current[col] = min(current[col] + delta, 99.0)

            current["tokens_per_second"] *= float(rng.uniform(1.02, 1.06))
            current["latency_ms"] *= float(rng.uniform(0.95, 0.98))

            if is_oss:
                current["cost_input_per_1m"] = 0.0
            else:
                current["cost_input_per_1m"] *= float(rng.uniform(0.97, 0.99))

            rows.append(
                {
                    "month": month,
                    "model_name": model_name,
                    "mmlu_score": round(current["mmlu_score"], 2),
                    "humaneval_score": round(current["humaneval_score"], 2),
                    "math_score": round(current["math_score"], 2),
                    "hellaswag_score": round(current["hellaswag_score"], 2),
                    "arc_score": round(current["arc_score"], 2),
                    "tokens_per_second": round(current["tokens_per_second"], 2),
                    "latency_ms": round(current["latency_ms"], 2),
                    "cost_input_per_1m": round(current["cost_input_per_1m"], 4),
                }
            )

    return pd.DataFrame(rows)


if __name__ == "__main__":
    df_static = build_static_dataset()
    print(f"Static dataset shape: {df_static.shape}")
    print(df_static.head(3).to_string())

    df_monthly = build_monthly_dataset()
    print(f"\nMonthly dataset shape: {df_monthly.shape}")
    print(df_monthly.head(3).to_string())
